apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-helm
  namespace: argocd

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      
    automated:
      prune: true
      selfHeal: true

  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.3
    helm:
      valuesObject:
        fullnameOverride: external-dns
        provider: cloudflare
        domainFilters: ["${DOMAIN}"]
        policy: sync
        txtOwnerId: "k8s-${ENVIRONMENT}"

        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-key
                key: apiKey
          - name: CF_API_EMAIL
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-key
                key: email

        resources:
          requests:
            cpu: 75m
            memory: 200Mi
          limits:
            cpu: 75m
            memory: 200Mi

        servicemonitor:
          enabled: true # true
          labels:
            prometheus.io/scrap-with: kube-prometheus-stack

        logFormat: json
        podDisruptionBudget:
          enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns

